/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as DietPlansRouteImport } from './routes/diet-plans'
import { Route as IndexRouteImport } from './routes/index'

const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlansRoute = DietPlansRouteImport.update({
  id: '/diet-plans',
  path: '/diet-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diet-plans': typeof DietPlansRoute
  '/supplements': typeof SupplementsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diet-plans': typeof DietPlansRoute
  '/supplements': typeof SupplementsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diet-plans': typeof DietPlansRoute
  '/supplements': typeof SupplementsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diet-plans' | '/supplements' | '/trainers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diet-plans' | '/supplements' | '/trainers'
  id: '__root__' | '/' | '/diet-plans' | '/supplements' | '/trainers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DietPlansRoute: typeof DietPlansRoute
  SupplementsRoute: typeof SupplementsRoute
  TrainersRoute: typeof TrainersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-plans': {
      id: '/diet-plans'
      path: '/diet-plans'
      fullPath: '/diet-plans'
      preLoaderRoute: typeof DietPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DietPlansRoute: DietPlansRoute,
  SupplementsRoute: SupplementsRoute,
  TrainersRoute: TrainersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
